name:  Actions Workflow
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: saludo
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Daniel Catalan
      - name: Log Greeting Time
        run: echo "${{ steps.saludo.outputs.time}}"